# Generated by Django 3.1.1 on 2020-10-17 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examen_et_concours', '0002_auto_20201016_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='examen_et_concours.country'),
        ),
    ]
