# Generated by Django 3.1.1 on 2020-10-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen_et_concours', '0003_auto_20201017_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.CharField(default='Aucun', max_length=100, verbose_name='Nom'),
        ),
    ]
