# Generated by Django 3.1.1 on 2020-10-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen_et_concours', '0004_auto_20201017_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
