# Generated by Django 3.1.1 on 2020-11-21 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examen_et_concours', '0006_auto_20201120_0455'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='evaluation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='examen_et_concours.evaluation'),
        ),
        migrations.AddField(
            model_name='matter',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='examen_et_concours.level'),
        ),
    ]
