# Generated by Django 3.1.1 on 2020-11-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen_et_concours', '0007_auto_20201121_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matter',
            name='level',
        ),
        migrations.AddField(
            model_name='matter',
            name='level',
            field=models.ManyToManyField(blank=True, null=True, to='examen_et_concours.Level'),
        ),
    ]
