# Generated by Django 3.1.1 on 2020-11-21 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examen_et_concours', '0008_auto_20201121_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matter',
            name='level',
        ),
        migrations.AddField(
            model_name='matter',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='examen_et_concours.level'),
        ),
    ]
