# Generated by Django 3.1.1 on 2020-11-21 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20201121_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poste',
            name='title',
            field=models.CharField(blank=True, default='reponse', max_length=60),
        ),
    ]
